<a href="https://colab.research.google.com/github/Srivardhan27/Heart-Disease-prediction/blob/main/heart_disesase_prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
heart_data = pd.read_csv('/content/HeartDiseaseTrain-Test.csv')

In [4]:
heart_data.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [5]:
heart_data.tail()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
1020,59,Male,Atypical angina,140,221,Lower than 120 mg/ml,ST-T wave abnormality,164,Yes,0.0,Downsloping,Zero,Fixed Defect,1
1021,60,Male,Typical angina,125,258,Lower than 120 mg/ml,Normal,141,Yes,2.8,Flat,One,Reversable Defect,0
1022,47,Male,Typical angina,110,275,Lower than 120 mg/ml,Normal,118,Yes,1.0,Flat,One,Fixed Defect,0
1023,50,Female,Typical angina,110,254,Lower than 120 mg/ml,Normal,159,No,0.0,Downsloping,Zero,Fixed Defect,1
1024,54,Male,Typical angina,120,188,Lower than 120 mg/ml,ST-T wave abnormality,113,No,1.4,Flat,One,Reversable Defect,0

In [6]:
heart_data.shape
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   object
 2   chest_pain_type                1025 non-null   object
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   object
 6   rest_ecg                       1025 non-null   object
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   object
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object
 11  vessels_colored_by_flourosopy  1025 non-null   object
 12  thalassemia                    1025 non-null   object
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 112.2+ KB

In [7]:
heart_data.shape

(1025, 14)

In [8]:
heart_data.isnull().sum()

age                              0
sex                              0
chest_pain_type                  0
resting_blood_pressure           0
cholestoral                      0
fasting_blood_sugar              0
rest_ecg                         0
Max_heart_rate                   0
exercise_induced_angina          0
oldpeak                          0
slope                            0
vessels_colored_by_flourosopy    0
thalassemia                      0
target                           0
dtype: int64

In [9]:
heart_data.describe()

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,target
count,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000
mean,54.434146,131.611707,246.00000,149.114146,1.071512,0.513171
std,9.072290,17.516718,51.59251,23.005724,1.175053,0.500070
min,29.000000,94.000000,126.00000,71.000000,0.000000,0.000000
25%,48.000000,120.000000,211.00000,132.000000,0.000000,0.000000
50%,56.000000,130.000000,240.00000,152.000000,0.800000,1.000000
75%,61.000000,140.000000,275.00000,166.000000,1.800000,1.000000
max,77.000000,200.000000,564.00000,202.000000,6.200000,1.000000

In [10]:
heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [11]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [12]:
print(X)

      age     sex  chest_pain_type  resting_blood_pressure  cholestoral  \
0      52    Male   Typical angina                     125          212
1      53    Male   Typical angina                     140          203
2      70    Male   Typical angina                     145          174
3      61    Male   Typical angina                     148          203
4      62  Female   Typical angina                     138          294
...   ...     ...              ...                     ...          ...
1020   59    Male  Atypical angina                     140          221
1021   60    Male   Typical angina                     125          258
1022   47    Male   Typical angina                     110          275
1023   50  Female   Typical angina                     110          254
1024   54    Male   Typical angina                     120          188

         fasting_blood_sugar               rest_ecg  Max_heart_rate  \
0       Lower than 120 mg/ml  ST-T wave abnormality             168
1     Greater than 120 mg/ml                 Normal             155
2       Lower than 120 mg/ml  ST-T wave abnormality             125
3       Lower than 120 mg/ml  ST-T wave abnormality             161
4     Greater than 120 mg/ml  ST-T wave abnormality             106
...                      ...                    ...             ...
1020    Lower than 120 mg/ml  ST-T wave abnormality             164
1021    Lower than 120 mg/ml                 Normal             141
1022    Lower than 120 mg/ml                 Normal             118
1023    Lower than 120 mg/ml                 Normal             159
1024    Lower than 120 mg/ml  ST-T wave abnormality             113

     exercise_induced_angina  oldpeak        slope  \
0                         No      1.0  Downsloping
1                        Yes      3.1    Upsloping
2                        Yes      2.6    Upsloping
3                         No      0.0  Downsloping
4                         No      1.9         Flat
...                      ...      ...          ...
1020                     Yes      0.0  Downsloping
1021                     Yes      2.8         Flat
1022                     Yes      1.0         Flat
1023                      No      0.0  Downsloping
1024                      No      1.4         Flat

     vessels_colored_by_flourosopy        thalassemia
0                              Two  Reversable Defect
1                             Zero  Reversable Defect
2                             Zero  Reversable Defect
3                              One  Reversable Defect
4                            Three       Fixed Defect
...                            ...                ...
1020                          Zero       Fixed Defect
1021                           One  Reversable Defect
1022                           One       Fixed Defect
1023                          Zero       Fixed Defect
1024                           One  Reversable Defect

[1025 rows x 13 columns]

In [13]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [15]:
print(X.shape, X_train.shape, X_test.shape)

(1025, 13) (820, 13) (205, 13)

In [16]:
model = LogisticRegression()

In [23]:
model.fit(X_train_encoded, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
# Identify categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns

# Apply one-hot encoding
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# Check the shape of the encoded dataframes
print(X_train_encoded.shape)
print(X_test_encoded.shape)

(820, 22)
(205, 22)

In [24]:
# accuracy on training data
X_train_prediction = model.predict(X_train_encoded)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.8695121951219512

In [26]:
input_data = (62, 'Female', 'Typical angina', 140, 268, 'Greater than 120 mg/ml', 'Normal', 160, 'No', 3.6, 'Flat', 'Two', 'Fixed Defect')

# Create a DataFrame from the input data
input_df = pd.DataFrame([input_data], columns=X.columns)

# Identify categorical columns (same as during training)
categorical_cols = X.select_dtypes(include='object').columns

# Apply one-hot encoding to the input data
input_encoded = pd.get_dummies(input_df, columns=categorical_cols, drop_first=True)

# Ensure the input data has the same columns as the training data
# Add missing columns with a value of 0
missing_cols = set(X_train_encoded.columns) - set(input_encoded.columns)
for c in missing_cols:
    input_encoded[c] = 0

# Ensure the order of columns is the same
input_encoded = input_encoded[X_train_encoded.columns]


prediction = model.predict(input_encoded)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[1]
The Person has Heart Disease